import { Inter } from "next/font/google";
import "./globals.css";
import SessionContext from "./context/SessionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionContext>{children}</SessionContext>
      </body>
    </html>
  );
}
